### ISSUE TITLE
大佬好强啊

### ISSUE THREAD

**Issue by ZizhuoWang** [Attt/Anyproxy-fgo-rule#1]
我用下试试😂

**Comment by ZizhuoWang** [comment]
真的可以用诶！
谢谢大佬！

**Comment by ZizhuoWang** [comment]
大佬您的QQ是叫冈伦吗？头像很像诶。。。

**Comment by Attt** [comment]
....这，竟然有人看到这个了....
不是我的QQ，我好久没用过QQ了

2018-04-25 13:52 GMT+08:00 ZizhuoWang <notifications@github.com>:
