### ISSUE TITLE
error 1.21

### ISSUE THREAD

**Issue by fabiopr2** [Attt/Anyproxy-fgo-rule#10]
get error on fiddler

https://i.imgur.com/fI1oAt1.png

**Comment by fabiopr2** [comment]
just ignore

**Comment by Attt** [comment]
this is a js script only for *anyproxy*, use fiddler you should edit the function "onBeforeResponse" in fiddler script which more like C#.

example:
`static function OnBeforeResponse(oSession: Session){
    if(oSession.responseCode == 200){
         // modify the battle json data here
    }
}`

**Comment by Attt** [comment]
@fabiopr2 @Alphayellowcat check out the [fiddlerScript.js](https://github.com/Attt/Anyproxy-fgo-rule/blob/master/ext/fiddlerScript.js), replace the same funtion in ur script.

**Comment by Alphayellowcat** [comment]
thanks sir.
