### ISSUE TITLE
且用且珍惜

### ISSUE THREAD

**Issue by einnse** [Attt/Anyproxy-fgo-rule#13]
官方已经注意到这个repo了。。下次更新应该和谐掉了，希望不会大面积封禁账号。

**Comment by ZizhuoWang** [comment]
官方注意到怎么说，跳跳们已经满世界bb了吗。。。。

**Comment by einnse** [comment]
[https://i.loli.net/2018/08/02/5b62546cb733a.jpg](url) @ZizhuoWang nga上官方人的回复

**Comment by ZizhuoWang** [comment]
。。。
2333
