### ISSUE TITLE
IOS测试时永远跑芙芙

### ISSUE THREAD

**Issue by BillHMax** [Attt/Anyproxy-fgo-rule#7]
证书也认证了，关于本机那里的证书信任也开了，代理服务器也设置了，在电脑上测试了模拟器也可以，但是一到苹果上就不行，永远卡在跑芙芙那里是怎么回事？客户端上也没有反应

**Comment by ZizhuoWang** [comment]
苹果手机其他的http请求可以正常通过anyproxy吗？
fgo报的是010101还是020202错误？

**Comment by BillHMax** [comment]
其他的http请求无法通过anyproxy，应该说设置了代理之后连网页都打不开，实际上扫码下载证书也出现了问题，证书是直接下载在电脑再传输到手机的
fgo的错误是010101

**Comment by ZizhuoWang** [comment]
...你的手机和电脑在同一个局域网下吗？

**Comment by BillHMax** [comment]
另一台手机开的热点给电脑跟苹果用的

**Comment by ZizhuoWang** [comment]
emmm
看一下你的手机热点给电脑分配的ip地址是多少，是不是写错了。。。不是写百度查到的ip，应该是局域网ip。

**Comment by BillHMax** [comment]
并且经过测试可以使用fiddler4进行代理抓包，可能是anyproxy的问题

**Comment by kaenorma** [comment]
在iphone的 ‘ 设置-》通用-》关于本机-》证书信任设置  ’ 中对AnyProxy完全信任就可以了
