### ISSUE TITLE
如何修改英灵携带的礼装

### ISSUE THREAD

**Issue by BillHMax** [Attt/Anyproxy-fgo-rule#8]
抓了包感觉应该是能改的但是不知道是改哪个属性

**Comment by BillHMax** [comment]
已解决

**Comment by ZizhuoWang** [comment]
可以分享一下你是怎么改的吗😂？
比如如果想把非满破礼装改成满破，怎么改？

**Comment by BillHMax** [comment]
用fiddler抓了包看了一下，每个礼装技能都有对应的ID，把礼装技能改成想要的礼装ID就可以了
if (svts[i]['parentSvtId'] != undefined) {
						svts[i]['skillId1'] = 礼装ID;
                                               //礼装ID类型为Number
					}
根据抓到的包的规律来看，将原礼装ID+1就是对应的满破礼装

**Comment by ZizhuoWang** [comment]
好的，非常感谢👍

**Comment by kaenorma** [comment]
这个svts[i]['skillId1']是李庄普通技能(比如甜蜜水晶的50np+无敌贯通)，
活动技能是svts[i]['skillId2'],掉落物加成、倍卡在这里
但是凋落物结算不是依据battlesetup的，所以改凋落物加成是没有用的。
比如
if (svts[i]['parentSvtId'] != undefined) {
//执行下列语句，从者在战斗中将拥有宝石翁的效果(100np)和尼禄倍卡的活动效果(200活动威力)
                        svts[i]['skillId2']=992707;//李庄技能2改为尼禄倍卡
                        svts[i]['skillId1']=990068;//李庄技能1改为宝石翁
                        }
                        
if (svts[i]['parentSvtId'] != undefined) {
//执行下列语句，从者在战斗中将拥有宝石翁的效果(100np)和尼禄掉落的活动效果(+2花瓣)
//但是在掉落物结算和掉落物查看时，不依据key=battlesetup的数值，所以加成还是真实携带李庄的加成
//类似的，将skill1改为羁绊加成，在战斗中可以看到效果是羁绊增加，但是结算时羁绊还是真实李庄加成
                        svts[i]['skillId2']=991053;//李庄技能2改为尼禄花瓣掉落
                        svts[i]['skillId1']=990068;//李庄技能1改为宝石翁
                        } 
////ID1=991053(满破花瓣)991049(满破尼禄倍卡)990680(满破甜蜜水晶)990068(满破宝石)
//ID2=992707(满破尼禄倍卡)
//有的满破李庄是奇数，有的是偶数，可能是中间的羁绊李庄之类的没有满破和未破之分导致的
